### ISSUE TITLE
Cannot call method 'info' of undefined

### ISSUE THREAD

**Issue by jjman505** [percolatestudio/meteor-migrations#44]
After running `meteor update` to upgrade from meteor version 1.1.0.3 to 1.2.0.2, I'm getting the following error:

```
W20151013-13:48:35.154(9)? (STDERR) /home/jeremy/.meteor/packages/meteor-tool/.1.1.9.1akpeh2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151013-13:48:35.154(9)? (STDERR) 						throw(ex);
W20151013-13:48:35.154(9)? (STDERR) 						      ^
W20151013-13:48:35.164(9)? (STDERR) TypeError: Cannot call method 'info' of undefined
W20151013-13:48:35.165(9)? (STDERR)     at Object.Migrations._migrateTo (meteor://💻app/packages/percolate_migrations/migrations_server.js:161:1)
W20151013-13:48:35.165(9)? (STDERR)     at Object.Migrations.migrateTo (meteor://💻app/packages/percolate_migrations/migrations_server.js:139:1)
W20151013-13:48:35.165(9)? (STDERR)     at meteor://💻app/server/migrations.js:74:1
W20151013-13:48:35.166(9)? (STDERR)     at meteor://💻app/server/migrations.js:74:1
W20151013-13:48:35.166(9)? (STDERR)     at /home/jeremy/Code/iohk/enrollment-app/attainenroll/.meteor/local/build/programs/server/boot.js:242:10
W20151013-13:48:35.166(9)? (STDERR)     at Array.forEach (native)
W20151013-13:48:35.166(9)? (STDERR)     at Function._.each._.forEach (/home/jeremy/.meteor/packages/meteor-tool/.1.1.9.1akpeh2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151013-13:48:35.167(9)? (STDERR)     at /home/jeremy/Code/iohk/enrollment-app/attainenroll/.meteor/local/build/programs/server/boot.js:137:5
```

Here are my package versions: https://gist.github.com/jjman505/0863738de256184616c5

**Comment by kristijanhusak** [comment]
Same here. I downgraded to `0.8.6` which works fine.

**Comment by workflow** [comment]
Solution is here: https://github.com/percolatestudio/meteor-migrations/issues/43

**Comment by jjman505** [comment]
Okay, great. Thanks @workflow!
